baseurl = "https://mikkalin.github.io/"
metaDataFormat = "yaml"
title = "咪卡咔"
theme = "blist"
hasCJKLanguage = true
googleAnalytics= "G-N0P6WLMPMK"
disqusShortname = 'mikaka'

DefaultContentLanguage = "tw"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 2
    languageName = "English"
    [languages.en.params]
      introTitle = "Mikakka"
      introSubtitle = "I'm Mika, not Mike."
      introPhoto = "/banner.jpg"
      logo = "/logo.png"
    [languages.en.params.homepage.social]
      title = "Find me here"
      description = "Too lazy to say my thoughts."

    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 2

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Categories"
        url = "categories"
        weight = 3

  [languages.tw]
    contentDir = "content/tw" #中文
    weight = 1
    languageName = "中文"
    title = "咪卡咔"
    description = "我是 Mika，不是 Mike。"
    [languages.tw.params]
      introTitle = "咪卡咔"
      introSubtitle = "我是 Mika，不是 Mike。"
      introPhoto = "/banner.jpg"
      logo = "/logo.png"
    [languages.tw.params.homepage.social]
      title = "Find me here"
      description = "話很多，懶得說。"

    [[languages.tw.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 2

    [[languages.tw.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 1

    [[languages.tw.menu.main]]
        name = "文章分類"
        url = "categories"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  # -- darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Mika · All rights reserved"
  favicon = "/icon/favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "disqus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Find me here"
  description = "話很多，懶得說。"

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/mika_kka"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://www.youtube.com/channel/UCBLqnjxZmp9oNvy2VZWG6WQ"
  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://www.instagram.com/mi.ka.kka/"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://www.facebook.com/profile.php?id=100088055116518"


[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
